[package]
name = "RusticFourier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
num-complex = "0.4"
num-traits = "0.2"
num = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
walkdir = "2"

# [profile.dev]
# rustflags = ["-A", "non_snake_case", "-A", "dead_code", "-A", "unused_imports", "-A", "unused_variables"]